# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


# SRC: https://projecteuler.net/problem=2
def sum_evens(limit=1000):
    x, y = [1, 2]
    num = y
    sum = 0

    # TODO? build fibonacci separately, and then filter?
    while(num <= limit):
        if (num % 2) == 0:
            sum += num

        num = x + y
        x = y
        y = num

    return sum


def test(limit: int, expected: list = None):
    result = sum_evens(limit)
    assert result == expected, f'expected:{expected}, got:{result}'
    print('✅', end='')


def test_all():
    #       2
    #       8
    test(10, expected=10)

    #       2
    #       8
    #      34
    test(100, expected=44)

    #       2
    #       8
    #      34
    #     144
    #     610
    test(1000, expected=798)

    #       2
    #       8
    #      34
    #     144
    #     610
    #    2584
    test(10000, expected=3382)

    #       2
    #       8
    #      34
    #     144
    #     610
    #    2584
    #   10946
    #   46368
    test(100000, expected=60696)

    #       2
    #       8
    #      34
    #     144
    #     610
    #    2584
    #   10946
    #   46368
    #  196418
    #  832040
    test(1000000, expected=1089154)

    #       2
    #       8
    #      34
    #     144
    #     610
    #    2584
    #   10946
    #   46368
    #  196418
    #  832040
    # 3524578
    test(4000000, expected=4613732)


if __name__ == '__main__':
    test_all()
