name: Verify
on:
  push:

env:
  ARCHITECTURE: x64
  NODE_VERSION: '16.X'
  PYTHON_VERSION: '3.10.5'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        problem:
          - Add Two Numbers
#         - All Wrong
          - Battleship
#         - Cafeteria
          - Director of Photography
          - Longest Common Prefix
          - Longest Palindromic Substring
          - Median of Two Sorted Arrays
          - Merged k Sorted Lists
          - Palindrome Number
          - Reverse String
          - Reverse to Make Equal
          - Roman to Integer
          - Shortest Common Prefixes
          - sum ABCs
          - Sum Even Fibonacci Numbers
          - Sum Multiples of 3 or 5
          - Summary of Ranges
          - Two Sum
          - Valid Parentheses
    name: "Test: ${{ matrix.problem }}"
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: ls
      run: ls -la

    - name: setup python@${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        architecture: ${{ env.ARCHITECTURE }}
        python-version: ${{ env.PYTHON_VERSION }}

    - name: setup node@${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: setup
      run: npm run setup:ci --if-present
    - name: npm install
      run: npm ci

    - name: lint
      run: npm run lint
      continue-on-error: true
    - name: aloe
      run: aloe features/${{ matrix.problem }}.feature --verbose
